### ISSUE TITLE
"cases per prefecture" revision and complement

### ISSUE THREAD

**Issue by lub-bee** [reustle/covid19japan#356] opened 2020-05-28 03:58 UTC
Since the pandemic seems to lose speed, the charts "daily trend" in "cases per prefecture" became a little hard to read, if not totally unreadable. 
![Chart hard to read](https://i.gyazo.com/1f6502cc90046c6351269ffdc56bd6d7.png)

It could be a little easier to understand it if we have a comparative column like "Days since last confirmed case" (hidden when there is case reported in the last 2 days)

**Comment by liquidx** [comment] 2020-07-11 01:45
That's a good idea to have days since the last confirmed cases for some of the less affected prefectures.

**Comment by IanUme** [comment] 2020-07-18 10:51
I’d like to recommend reverting the PR:
https://github.com/reustle/covid19japan/pull/384

For mobile users it was very easy to scroll to see how many new cases in your prefecture and neighboring prefectures (for example saitama, Tokyo and China). Now you need to scroll vertically and horizontally and it is much more difficult if you are on the edge of two regions (for example Kanto and Chubu).

I propose a few possible fixes:
1. Revert to before the PR
2. Revert to before the PR and separate the rows by region
3. Keep current UI but make the current horizontal scrolling vertical scroll. This will be a long list so a select region or hide regions would be necessary. 

I don’t do any web work so I probably can’t contribute reasonably. Sorry but thanks for the great site.

**Comment by liquidx** [comment] 2020-07-18 13:44
I agree with your feedback, though, this feedback is separate from the issue you have commented on. I have a change that I've been work on to improve the mobile layout #391

**Comment by IanUme** [comment] 2020-07-19 07:38
Ahh apologies on wrong issue. Glanced the issue too quickly. I think the new layout is definitely better for mobile than the last horizontal side scrolling version. I suppose a better issue is better. The most important stat to me is the current day case count followed by the day before (or rolling 7 day average of that data is available). This will show if the cases seem to be getting better or worse. Deceased count is not too important to me personally because the number is reflected much later than the confirmed date. 

I’m only one person though so the overall opinion of users is the most important.

**Comment by reustle** [comment] 2021-01-22 01:00
Thank you @IanUme - The changes discussed have long been merged, so I'll close this issue for now. Please feel free to comment if you have any further questions.

**Closed by reustle** 2021-01-22 01:00 UTC
Labels: enhancement
