### ISSUE TITLE
Adjust x and y axes / add labels to mini-graphs

### ISSUE THREAD

**Issue by ann-kilzer** [reustle/covid19japan#304] opened 2020-05-05 02:02 UTC
// Please tag @reustle in your newly created issue

I see that there are small graphs near the numbers at the top of the page, and a quick scan of these looks misleading because each graph line is of equal height, yet the values are different:

<img width="1280" alt="_15095__Coronavirus_Disease__COVID-19__Japan_Tracker" src="https://user-images.githubusercontent.com/4602369/81029336-715c6600-8ebf-11ea-8e2f-df651697fabb.png">

What are the values for the x and y axes? In one graph there are 15k confirmed cases, in another there are 500 deaths, yet the linear arrangement of the graphs gives an implied shared Y axis. 

I also can't determine the time interval of this data from the graph because the X axis has no labels.

**Comment by liquidx** [comment] 2020-05-05 02:23
Thanks for the feedback.

The problem is that we want to give people some relative trend they can see with the single number we previously showed.

They're not supposed to be comparable across each other, because as you say, the Y-axis is different. But if we scaled them all to the same axis, then you can't see the trend that deaths are rising or the number of tests are stable per-day.

But seems like the way we've arranged it makes people think they are on the same axis (in the more narrower layouts they are not all in one line so you don't get a sense they should be comparable.

**Comment by ann-kilzer** [comment] 2020-05-05 02:36
What if you added a small label on the top value of the Y axis? At least this would let viewers see what the max value is

**Comment by Kay-Cube** [comment] 2020-05-05 04:53
<img width="448" alt="Screen Shot 2020-05-05 at 13 51 42" src="https://user-images.githubusercontent.com/61060404/81035831-9c52b400-8ed7-11ea-8077-c89d35cc54de.png">
An example layout. 
Can we also align the note to the KPI title? eg. "Daily new cases" to "Confirmed"

**Comment by liquidx** [comment] 2020-05-05 06:21
How about like this?

<img width="436" alt="Screen Shot 2020-05-05 at 15 21 06" src="https://user-images.githubusercontent.com/72062/81039486-1ee17080-8ee4-11ea-93e9-a346443a3a38.png">

**Comment by Kay-Cube** [comment] 2020-05-05 06:27
I'm not quite sure. It left a lot space on the right... makes the box looks unbalanced (visual weight is not centered)
I like the fact you can compare the last point to the highest point, but probably users can still do that in other charts.
Also tiny point, can we align the axis name to the KPI title? (eg "Daily new cases" left aligned with "Confirmed")

**Comment by liquidx** [comment] 2020-05-05 06:36
Understood about the right hand margin. It's hard to put the max on the left because the chart doesn't always have space there (e.g. for Recovered it would be hard to put the label there. 

Right now the chart seems to be centered in the box where as all the text is left-aligned. If we make it left aligned, would that help?

I've been trying everything to try to align that bottom label but having no luck.

**Comment by liquidx** [comment] 2020-05-05 06:43
Ah, I realize what you meant, let me try something else to see if I can keep it centered but still only show the max.

**Comment by Kay-Cube** [comment] 2020-05-05 06:51
Re label:
Probably we don't need to add the exact number, but a rough scale. like Recovery is below 200.
Or another solution would be hover over and see the max number.

Re bottom text:
Is the problem because the text is in the box of the graph? If the text is outside graph, it should be able to align with other text.

**Comment by liquidx** [comment] 2020-05-05 07:06
I think this one is closer to what you were suggesting - only drawing a ceiling number that is a round number.

<img width="624" alt="Screen Shot 2020-05-05 at 15 59 45" src="https://user-images.githubusercontent.com/72062/81042043-3cb1d400-8eea-11ea-96c3-91600869d889.png">

**Comment by liquidx** [comment] 2020-05-05 07:38
Merged and now live. Hopefully this helps if people are comparing between those charts for now.

**Closed by liquidx** 2020-05-05 07:38 UTC

**Comment by ann-kilzer** [comment] 2020-05-05 09:46
Wow cool! Thanks for incorporating my feedback!
