### ISSUE TITLE
add big daily tests graph

### ISSUE THREAD

**Issue by jaroslaw-weber** [reustle/covid19japan#334] opened 2020-05-14 06:22 UTC
It would be nice to have bigger graph for how many tests were done.
There is a lot of discussion about "Japan is not testing enough". I think it would be useful to pair "new daily cases" with "new daily tests" to get "% of tests that are positive (daily)".

**Comment by liquidx** [comment] 2020-05-14 11:33
Duplicate of #80

The problem with this is that the daily test numbers fluctuate a lot and quite inaccurate, so it'll be very noisy. 

Some prefectures do already make this info available, especially Tokyo:
https://stopcovid19.metro.tokyo.lg.jp/

**Comment by liquidx** [comment] 2020-05-14 11:36
Duplicate of #80

**Closed by liquidx** 2020-05-14 11:36 UTC
